name: 'gaming_dwh_project'
version: '1.0'
config-version: 2
test-paths: ["gaming_dwh_project/tests"]

profile: gaming_dwh_project  
model-paths: ["gaming_dwh_project"]
target-path: "target"
clean-targets:
  - "target"
models:
  gaming_dwh_project:
    raw:
      +materialized: table
    stage:
      +materialized: view
    mart:
      +materialized: view
